name: petibm-examples
channels:
- defaults
dependencies:
- python ==3.6.8
- pip ==19.1.1
- h5py ==2.9.0
- lxml ==4.3.1
- matplotlib ==3.0.2
- numpy ==1.16.2
- pyyaml ==5.2
- scipy ==1.2.1
- pip:
  - git+https://github.com/mesnardo/petibmpy@v0.2
