# 296x295 (87320)
mesh:
- direction: x
  start: -15.0
  subDomains:
  - cells: 68
    end: -2.0
    stretchRatio: 0.9523809524
  - cells: 160
    end: 2.0
    stretchRatio: 1.0
  - cells: 68
    end: 15.0
    stretchRatio: 1.05
- direction: y
  start: -15.0
  subDomains:
  - cells: 66
    end: -3.0
    stretchRatio: 0.9523809524
  - cells: 160
    end: 1.0
    stretchRatio: 1.0
  - cells: 69
    end: 15.0
    stretchRatio: 1.05

flow:
  nu: 0.029321531433504737
  initialVelocity: [0.0, 0.0]
  boundaryConditions:
    - location: xMinus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]
    - location: xPlus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]
    - location: yMinus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]
    - location: yPlus
      u: [DIRICHLET, 0.0]
      v: [DIRICHLET, 0.0]

parameters:
  dt: 0.005
  startStep: 0
  nt: 3200
  nsave: 100
  nrestart: 800
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  velocitySolver:
    type: CPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info

bodies:
  - type: points
    name: ellipse
    file: ellipse.body
    kinematics:
      f: 0.25
      A0: 2.8
      alpha0: 1.5707963267948966
      beta: 0.7853981633974483
      phi: 0.0
      c: 1.0
      center: [0.0, 0.0]
