mesh:
  - direction: x
    start: 0.0
    subDomains:
      - end: 1.0
        cells: 128
        stretchRatio: 1.0
  - direction: y
    start: 0.0
    subDomains:
      - end: 1.0
        cells: 128
        stretchRatio: 1.0

flow:
    nu: 0.001
    initialVelocity: [0.0, 0.0]
    boundaryConditions:
      - location: xMinus
        u: [DIRICHLET, 0.0]
        v: [DIRICHLET, 0.0]
      - location: xPlus
        u: [DIRICHLET, 0.0]
        v: [DIRICHLET, 0.0]
      - location: yMinus
        u: [DIRICHLET, 0.0]
        v: [DIRICHLET, 0.0]
      - location: yPlus
        u: [DIRICHLET, 1.0]
        v: [DIRICHLET, 0.0]

parameters:
    dt: 0.004
    startStep: 0
    nt: 10000
    nsave: 10000
    nrestart: 10000
    convection: ADAMS_BASHFORTH_2
    diffusion: CRANK_NICOLSON
    velocitySolver:
      type: CPU
      config: config/velocity_solver.info
    poissonSolver:
      type: CPU
      config: config/poisson_solver.info
