# 272x82x82 (1828928)
mesh:
- direction: x
  start: -10.0
  subDomains:
  - cells: 69
    end: -1.0
    stretchRatio: 0.9708737864
  - cells: 150
    end: 5.0
    stretchRatio: 1.0
  - cells: 53
    end: 10.0
    stretchRatio: 1.03
- direction: y
  start: -10.0
  subDomains:
  - cells: 16
    end: -1.0
    stretchRatio: 0.7692307692
  - cells: 50
    end: 1.0
    stretchRatio: 1.0
  - cells: 16
    end: 10.0
    stretchRatio: 1.3
- direction: z
  start: -10.0
  subDomains:
  - cells: 16
    end: -1.0
    stretchRatio: 0.7692307692
  - cells: 50
    end: 1.0
    stretchRatio: 1.0
  - cells: 16
    end: 10.0
    stretchRatio: 1.3

flow:
  nu: 0.006666666666666667
  initialVelocity: [1.0, 0.0, 0.0]
  boundaryConditions:
  - location: xMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
    w: [DIRICHLET, 0.0]
  - location: xPlus
    u: [CONVECTIVE, 1.0]
    v: [CONVECTIVE, 0.0]
    w: [CONVECTIVE, 0.0]
  - location: yMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
    w: [DIRICHLET, 0.0]
  - location: yPlus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
    w: [DIRICHLET, 0.0]
  - location: zMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
    w: [DIRICHLET, 0.0]
  - location: zPlus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
    w: [DIRICHLET, 0.0]

parameters:
  dt: 0.004
  startStep: 0
  nt: 2500
  nsave: 500
  nrestart: 500
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  velocitySolver:
    type: CPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info

bodies:
  - type: points
    file: sphere.body
